'use client';

import { useState } from 'react';
import { Copy, Check, FileCode, Shield, Globe, Lock } from 'lucide-react';
import { motion } from 'framer-motion';

export default function HtaccessGenerator() {
    const [redirects, setRedirects] = useState<{ from: string, to: string }[]>([]);
    const [https, setHttps] = useState(false);
    const [www, setWww] = useState<'none' | 'force-www' | 'force-non-www'>('none');
    const [blockedIps, setBlockedIps] = useState('');
    const [copied, setCopied] = useState(false);

    const generateCode = () => {
        let code = `# Generated by SEO Studio .htaccess Generator\nRewriteEngine On\n\n`;

        // HTTPS
        if (https) {
            code += `# Force HTTPS\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n`;
        }

        // WWW
        if (www === 'force-www') {
            code += `# Force WWW\nRewriteCond %{HTTP_HOST} !^www\.\nRewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]\n\n`;
        } else if (www === 'force-non-www') {
            code += `# Force Non-WWW\nRewriteCond %{HTTP_HOST} ^www\.(.*)$\nRewriteRule ^(.*)$ https://%1/$1 [R=301,L]\n\n`;
        }

        // Redirects
        if (redirects.length > 0) {
            code += `# 301 Redirects\n`;
            redirects.forEach(r => {
                if (r.from && r.to) code += `Redirect 301 ${r.from} ${r.to}\n`;
            });
            code += `\n`;
        }

        // Block IPs
        if (blockedIps) {
            code += `# Block IPs\norder allow,deny\ndeny from ${blockedIps.split(',').map(ip => ip.trim()).join('\ndeny from ')}\nallow from all\n`;
        }

        return code;
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(generateCode());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="htaccess-gen max-w-5xl mx-auto flex flex-col lg:flex-row gap-8">
            <div className="flex-1 space-y-6">
                <div className="bg-surface p-6 rounded-2xl border border-border shadow-sm">
                    <h3 className="font-bold border-b border-border pb-4 mb-4 flex items-center gap-2"><Lock size={18} /> Security & Domain</h3>

                    <div className="space-y-4">
                        <label className="flex items-center gap-3 cursor-pointer p-3 bg-background border border-border rounded-lg hover:border-primary transition-colors">
                            <input type="checkbox" checked={https} onChange={e => setHttps(e.target.checked)} className="w-5 h-5 accent-primary" />
                            <div>
                                <span className="font-medium block">Force HTTPS</span>
                                <span className="text-xs text-secondary">Redirect all HTTP traffic to HTTPS</span>
                            </div>
                        </label>

                        <div className="grid grid-cols-2 gap-4">
                            <label className={`cursor-pointer p-3 border rounded-lg text-center ${www === 'force-www' ? 'bg-primary/5 border-primary' : 'border-border bg-background'}`}>
                                <input type="radio" name="www" className="hidden" onChange={() => setWww('force-www')} checked={www === 'force-www'} />
                                <span className="font-medium text-sm">Force WWW</span>
                            </label>
                            <label className={`cursor-pointer p-3 border rounded-lg text-center ${www === 'force-non-www' ? 'bg-primary/5 border-primary' : 'border-border bg-background'}`}>
                                <input type="radio" name="www" className="hidden" onChange={() => setWww('force-non-www')} checked={www === 'force-non-www'} />
                                <span className="font-medium text-sm">Force Non-WWW</span>
                            </label>
                        </div>
                    </div>
                </div>

                <div className="bg-surface p-6 rounded-2xl border border-border shadow-sm">
                    <h3 className="font-bold border-b border-border pb-4 mb-4 flex items-center gap-2"><Globe size={18} /> 301 Redirects</h3>
                    {redirects.map((r, i) => (
                        <div key={i} className="flex gap-2 mb-2">
                            <input placeholder="/old-page.html" value={r.from} onChange={e => {
                                const newR = [...redirects];
                                newR[i].from = e.target.value;
                                setRedirects(newR);
                            }} className="flex-1 p-2 bg-background border border-border rounded-lg text-sm" />
                            <input placeholder="https://example.com/new" value={r.to} onChange={e => {
                                const newR = [...redirects];
                                newR[i].to = e.target.value;
                                setRedirects(newR);
                            }} className="flex-1 p-2 bg-background border border-border rounded-lg text-sm" />
                        </div>
                    ))}
                    <button onClick={() => setRedirects([...redirects, { from: '', to: '' }])} className="text-sm text-primary font-medium hover:underline">+ Add Redirect Rule</button>
                </div>

                <div className="bg-surface p-6 rounded-2xl border border-border shadow-sm">
                    <h3 className="font-bold border-b border-border pb-4 mb-4 flex items-center gap-2"><Shield size={18} /> Block IP Addresses</h3>
                    <textarea
                        className="w-full h-24 p-3 bg-background border border-border rounded-lg text-sm"
                        placeholder="192.168.1.1, 10.0.0.1 (Comma separated)"
                        value={blockedIps}
                        onChange={e => setBlockedIps(e.target.value)}
                    />
                </div>
            </div>

            <div className="lg:w-1/3">
                <div className="bg-[#1e1e1e] rounded-2xl overflow-hidden shadow-xl sticky top-24">
                    <div className="bg-[#2d2d2d] px-4 py-3 flex justify-between items-center border-b border-[#3e3e3e]">
                        <span className="text-xs font-mono text-gray-400">.htaccess</span>
                        <button onClick={copyToClipboard} className="text-gray-400 hover:text-white transition-colors">
                            {copied ? <Check size={16} className="text-green-500" /> : <Copy size={16} />}
                        </button>
                    </div>
                    <pre className="p-4 text-sm font-mono text-green-400 overflow-x-auto whitespace-pre-wrap leading-relaxed h-[500px] overflow-y-auto">
                        {generateCode()}
                    </pre>
                </div>
            </div>
        </div>
    );
}
