'use client';

import { useState } from 'react';
import { Shield, Download, Plus, Trash2, FileText, Check, PlusCircle, ShieldAlert, Code2, Bot } from 'lucide-react';
import { Button, Input, Select, Card } from '@/components/ui/Core';
import { motion, AnimatePresence } from 'framer-motion';

export default function RobotsTxtBuilder() {
    const [rules, setRules] = useState<{ agent: string, action: 'Allow' | 'Disallow', path: string }[]>([
        { agent: '*', action: 'Disallow', path: '/admin/' },
        { agent: '*', action: 'Allow', path: '/' }
    ]);
    const [sitemap, setSitemap] = useState('');
    const [output, setOutput] = useState('');

    const addRule = () => setRules([...rules, { agent: '*', action: 'Disallow', path: '' }]);
    const removeRule = (idx: number) => setRules(rules.filter((_, i) => i !== idx));
    const updateRule = (idx: number, key: string, val: string) => {
        const newRules = [...rules];
        (newRules[idx] as any)[key] = val;
        setRules(newRules);
    };

    const generateFile = () => {
        let text = "# Robots.txt generated by SEOStudio Execution Engine\n";
        text += `# Timestamp: ${new Date().toISOString()}\n\n`;
        rules.forEach(rule => {
            text += `User-agent: ${rule.agent || '*'}\n`;
            text += `${rule.action}: ${rule.path || '/'}\n\n`;
        });
        if (sitemap.trim()) {
            text += `Sitemap: ${sitemap}\n`;
        }
        setOutput(text);
    };

    const downloadFile = () => {
        const blob = new Blob([output], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'robots.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-10">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                {/* Configuration Panel */}
                <div className="lg:col-span-5 space-y-6">
                    <div className="space-y-4">
                        <label className="text-[10px] font-black uppercase tracking-widest text-muted-fg px-1 flex items-center gap-2">
                            <Bot size={12} className="text-accent" /> Indexing Authority
                        </label>
                        <Input
                            placeholder="Sitemap URL (Optional) e.g. https://site.com/sitemap.xml"
                            value={sitemap}
                            onChange={(e: any) => setSitemap(e.target.value)}
                            className="font-bold"
                        />
                    </div>

                    <div className="space-y-4">
                        <div className="flex items-center justify-between px-1">
                            <label className="text-[10px] font-black uppercase tracking-widest text-muted-fg">Instruction Sets</label>
                            <span className="text-[10px] font-bold text-accent">{rules.length} Directives</span>
                        </div>

                        <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2 no-scrollbar">
                            <AnimatePresence initial={false}>
                                {rules.map((rule, idx) => (
                                    <motion.div
                                        key={idx}
                                        initial={{ opacity: 0, y: 10 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        exit={{ opacity: 0, x: 20 }}
                                    >
                                        <Card className="p-4 bg-muted/20 border-border space-y-3 group hover:border-accent/40 transition-fast">
                                            <div className="flex gap-2">
                                                <div className="flex-1">
                                                    <Select
                                                        value={rule.agent}
                                                        onChange={(e: any) => updateRule(idx, 'agent', e.target.value)}
                                                        className="text-xs font-bold"
                                                    >
                                                        <option value="*">All User-Agents (*)</option>
                                                        <option value="Googlebot">Googlebot</option>
                                                        <option value="Bingbot">Bingbot</option>
                                                        <option value="Yandex">Yandex</option>
                                                        <option value="Baiduspider">Baiduspider</option>
                                                    </Select>
                                                </div>
                                                <div className="flex-1">
                                                    <Select
                                                        value={rule.action}
                                                        onChange={(e: any) => updateRule(idx, 'action', e.target.value)}
                                                        className={`text-xs font-black uppercase ${rule.action === 'Allow' ? 'text-green-500' : 'text-red-500'}`}
                                                    >
                                                        <option value="Allow">Allow Access</option>
                                                        <option value="Disallow">Disallow Access</option>
                                                    </Select>
                                                </div>
                                                <Button variant="ghost" size="sm" onClick={() => removeRule(idx)} className="text-muted-fg hover:text-red-500">
                                                    <Trash2 size={14} />
                                                </Button>
                                            </div>
                                            <div className="relative">
                                                <div className="absolute left-3 top-1/2 -translate-y-1/2 text-[10px] font-black pointer-events-none text-muted-fg">PATH</div>
                                                <Input
                                                    placeholder="/admin/"
                                                    value={rule.path}
                                                    onChange={(e: any) => updateRule(idx, 'path', e.target.value)}
                                                    className="pl-14 text-xs font-mono"
                                                />
                                            </div>
                                        </Card>
                                    </motion.div>
                                ))}
                            </AnimatePresence>
                        </div>

                        <Button variant="secondary" onClick={addRule} className="w-full border-dashed">
                            <PlusCircle size={16} /> Append Directive
                        </Button>
                    </div>

                    <Button
                        variant="primary"
                        className="w-full py-4 shadow-xl"
                        onClick={generateFile}
                        disabled={rules.length === 0}
                    >
                        Compile Security Policy <Shield size={16} fill="currentColor" />
                    </Button>
                </div>

                {/* Preview Panel */}
                <div className="lg:col-span-7 space-y-4 h-full min-h-[500px] flex flex-col">
                    <div className="flex items-center justify-between px-1">
                        <label className="text-[10px] font-black uppercase tracking-widest text-muted-fg flex items-center gap-2">
                            <Code2 size={12} className="text-accent" /> Compiled Logic
                        </label>
                        {output && (
                            <Button variant="ghost" size="sm" onClick={downloadFile} className="text-accent">
                                <Download size={14} /> Fetch .TXT File
                            </Button>
                        )}
                    </div>

                    <div className="relative flex-1 bg-muted/10 border-2 border-border rounded-2xl overflow-hidden min-h-[450px]">
                        <AnimatePresence mode="wait">
                            {output ? (
                                <motion.div
                                    key="result"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    className="p-8 h-full font-mono text-sm leading-relaxed overflow-auto no-scrollbar"
                                >
                                    <div className="text-muted-fg/40 select-none mb-6 italic">// Instructions targeting crawler behaviors</div>
                                    <pre className="text-fg whitespace-pre-wrap">{output}</pre>
                                </motion.div>
                            ) : (
                                <motion.div
                                    key="empty"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    className="absolute inset-0 flex flex-col items-center justify-center text-center space-y-6 opacity-30"
                                >
                                    <ShieldAlert size={64} className="text-muted-fg" />
                                    <p className="text-xs font-black italic max-w-xs uppercase tracking-widest">Awaiting Security Configuration</p>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </div>
            </div>
        </div>
    );
}
